# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('document_country_of_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('document_series', models.IntegerField(blank=True, null=True)),
                ('id_document_expiration_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=100, null=True)),
                ('document_scan', models.ImageField(blank=True, upload_to='users/%Y/%m/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
