# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180501_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.NullBooleanField(),
        ),
    ]
