# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_currency', models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin'), ('XRP', 'RIPPLE')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('unix_timestamp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'cryptocurrency',
                'verbose_name_plural': 'cryptocurrencies',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyTrendingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(blank=True, max_length=30)),
                ('lastvolume', models.DecimalField(decimal_places=9, max_digits=18, null=True)),
                ('lastvolumeto', models.DecimalField(decimal_places=9, max_digits=18, null=True)),
                ('lasttradeid', models.BigIntegerField(null=True)),
                ('openday', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('highday', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('lowday', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('open24hour', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('high24hour', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('low24hour', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('change24hour', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('changepct24hour', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('changeday', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('changepctday', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('supply', models.IntegerField()),
                ('mktcap', models.BigIntegerField(blank=True, null=True)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientAPI.CryptoCurrency')),
            ],
        ),
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=50)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientAPI.CryptoCurrency')),
            ],
            options={
                'verbose_name': 'fiat currency',
                'verbose_name_plural': 'fiat currencies',
            },
        ),
    ]
