# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-27 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_currency', models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('LTC', 'Litecoin'), ('XRP', 'RIPPLE')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('unix_timestamp', models.IntegerField()),
            ],
            options={
                'verbose_name': 'cryptocurrency',
                'verbose_name_plural': 'cryptocurrencies',
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='Currency_Trending_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(blank=True, max_length=30)),
                ('last_volume', models.DecimalField(decimal_places=9, max_digits=18)),
                ('last_volume_to', models.DecimalField(decimal_places=9, max_digits=18)),
                ('last_trade_id', models.BigIntegerField()),
                ('open_day', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('high_day', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('low_day', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('open_24_hours', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('high_24_hours', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('low_24_hours', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('change_24_hours', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('change_percent_24_hours', models.IntegerField()),
                ('change_day', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('change_percent_day', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('supply', models.IntegerField()),
                ('market_cap', models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientAPI.Crypto_Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Fiat_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=50)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientAPI.Crypto_Currency')),
            ],
            options={
                'verbose_name': 'fiat currency',
                'verbose_name_plural': 'fiat currencies',
            },
        ),
    ]
