# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytrendinginfo',
            name='mktcap',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='currencytrendinginfo',
            name='supply',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=18, null=True),
        ),
    ]
