# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-09 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='change_24_hours',
            new_name='change_24_hour',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='change_percent_24_hours',
            new_name='change_pct_24_hour',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='change_percent_day',
            new_name='change_pct_day',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='high_24_hours',
            new_name='high_24_hour',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='low_24_hours',
            new_name='low_24_hour',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='market_cap',
            new_name='mkt_cap',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='open_24_hours',
            new_name='open_24_hour',
        ),
    ]
