# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_trending_info',
            name='last_volume',
            field=models.DecimalField(db_column='lastvolume', decimal_places=9, max_digits=18),
        ),
    ]
