# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientAPI', '0002_auto_20181018_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytrendinginfo',
            name='mktcap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencytrendinginfo',
            name='supply',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
