# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientAPI', '0002_auto_20181013_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='change_24_hour',
            new_name='change24hour',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='change_day',
            new_name='changeday',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='change_pct_24_hour',
            new_name='changepct24hour',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='change_pct_day',
            new_name='changepctday',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='high_24_hour',
            new_name='high24hour',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='high_day',
            new_name='highday',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='low_24_hour',
            new_name='low24hour',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='low_day',
            new_name='lowday',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='mkt_cap',
            new_name='mktcap',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='open_24_hour',
            new_name='open24hour',
        ),
        migrations.RenameField(
            model_name='currency_trending_info',
            old_name='open_day',
            new_name='openday',
        ),
        migrations.RemoveField(
            model_name='currency_trending_info',
            name='last_trade_id',
        ),
        migrations.RemoveField(
            model_name='currency_trending_info',
            name='last_volume',
        ),
        migrations.RemoveField(
            model_name='currency_trending_info',
            name='last_volume_to',
        ),
        migrations.AddField(
            model_name='currency_trending_info',
            name='lasttradeid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='currency_trending_info',
            name='lastvolume',
            field=models.DecimalField(decimal_places=9, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='currency_trending_info',
            name='lastvolumeto',
            field=models.DecimalField(decimal_places=9, max_digits=18, null=True),
        ),
    ]
