# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientAPI', '0003_auto_20181013_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_trending_info',
            name='mktcap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
